import { Theme } from "@mui/material";
import { createStyles, makeStyles } from "@mui/styles";
import Colours from "../../Context/Theme/Colours";

const useStyles = makeStyles((theme: Theme) =>
  createStyles({
    root: {
      display: "flex",
      alignContent: "center",
      alignItems: "center",
      flexDirection: "column",
      flexWrap: "wrap",
      justifyContent: "center",
      justifyItems: "center",
      color: Colours.BW_02[theme.palette.mode],
      // border: `1px solid ${Colours.BW_02[theme.palette.mode]}`,
      // borderRadius: "10px",
      padding: "100px !important",
      background: Colours.BW[theme.palette.mode],
    },
    title: {
      display: "flex",
      justifyContent: "center",
      alignItems: "center",
      alignContent: "center",
      border: 0,
      borderRadius: 10,
      color: Colours.BW_02[theme.palette.mode],
      height: 50,
      padding: "10px",
      width: "auto",
      background: Colours.BW[theme.palette.mode],
      backgroundAttachment: "fixed",
    },
    subtitle: {
      display: "flex",
      justifyContent: "center",
      alignItems: "center",
      alignContent: "center",
      // background: "black",
      border: 0,
      borderRadius: 10,
      color: Colours.BW[theme.palette.mode],
      height: 50,
      padding: "10px",
      width: "auto",
      background: "linear-gradient(-20deg, rgb(0,0,0) 30%, #FF8E53 90%)",
      backgroundAttachment: "fixed",
    },
    players: {
      display: "flex",
      alignContent: "center",
      alignItems: "center",
      flexDirection: "row",
      justifyContent: "center",
      justifyItems: "center",
      flexWrap: "wrap",
      color: Colours.BW[theme.palette.mode],
      border: "1px solid black",
      borderRadius: "10px",
      padding: "1000px !important",
      width: "20rem",
      height: "47rem",
    },
    playerStats: {
      display: "flex",
      flexDirection: "column",
      textAlign: "center",
      alignItems: "center",
      background: Colours.BW[theme.palette.mode],
    },
    playerStatsBox: {
      display: "flex",
      flexDirection: "row",
      textAlign: "left",
      alignItems: "center",
    },
    paper: {
      display: "flex",
      flexDirection: "column",
      alignItems: "center",
      margin: "10px",
      marginBottom: "100px",
      padding: "20px",
      // border: '5px solid black',
      borderRadius: "10px",
      width: "90%",
    },
    table: {
      display: "flex",
      flexDirection: "column",
      alignItems: "center",
      margin: "10px",
      padding: "20px",
    },
    playerStatsPaper: {
      display: "flex",
      flexDirection: "column",
      textAlign: "center",
      alignItems: "center",
      flexWrap: "wrap",
      width: "90%",
      margin: "10px",
      marginBottom: 100,
      borderRadius: "10px",
    },
    defaultTable: {},
    images: {
      height: "200px",
      width: "200px",
    },
  })
);

export default useStyles;
